apiVersion: v1
kind: Pod
metadata:
  name: demo-cudia-lion01
spec:
  restartPolicy: Never
  containers:
    - name: demo-cuda
      image: "nvidia/cuda:11.0.3-devel-ubi8"
      command: ["sh", "-c", "sleep infinity"]
      resources:
        limits:
          memory: 4G
          cpu: 2
          nvidia.com/gpu: 1
  nodeSelector:
    kubernetes.io/hostname: lion01
