apiVersion: v1
kind: Pod
metadata:
  name: demo-python
spec:
  restartPolicy: Never
  containers:
  - env:
    - name: NUM
      value: '10'
    name: demo-python
    image: ddavila0/myubuntu:py3-20230901
    command: ["sh", "-c", "sleep infinity"]
    resources:
      limits:
        memory: 4G
        cpu: 2
        nvidia.com/gpu: 1
      requests:
        memory: 2G
        cpu: 1
        nvidia.com/gpu: 1
