apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  hostNetwork: true
  containers:
   - name: nginx
     image: nginx
     volumeMounts:
       - mountPath: /s3
         name: webroot
  volumes:
   - name: webroot
     persistentVolumeClaim:
       claimName: example-dataset
       readOnly: false
