apiVersion: v1
kind: Pod
metadata:
  name: demo-cuda
spec:
  restartPolicy: Never
  containers:
    - name: demo-cuda
      image: "nvidia/cuda:11.0.3-devel-ubi8"
      command: ["sh", "-c", "sleep infinity"]
      resources:
        limits:
          memory: 4G
          cpu: 2
          nvidia.com/gpu: 1
        requests:
          memory: 2G
          cpu: 1
          nvidia.com/gpu: 1
      volumeMounts:
       - mountPath: /s3
         name: s3-cudi
  volumes:
   - name: s3-cudi
     persistentVolumeClaim:
       claimName: example-dataset
       readOnly: false
  nodeSelector:
    kubernetes.io/hostname: atocatl-gpu-04.lamod.unam.mx
